
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA CLASS CONSOLE DOT ERROR IDENTIFICADOR LBRACE LBRACKET LPAREN MAIN NAMESPACE RBRACE RBRACKET RPAREN SEMICOLON STATIC STRING USING VOID WRITELINEprograma : using_decl namespace_declusing_decl : USING IDENTIFICADOR SEMICOLONnamespace_decl : NAMESPACE IDENTIFICADOR LBRACE class_decl RBRACEclass_decl : CLASS IDENTIFICADOR LBRACE method_decl RBRACEmethod_decl : STATIC VOID MAIN LPAREN STRING LBRACKET RBRACKET IDENTIFICADOR RPAREN LBRACE statement RBRACEstatement : CONSOLE DOT WRITELINE LPAREN CADENA RPAREN SEMICOLON'
    
_lr_action_items = {'USING':([0,],[3,]),'$end':([1,4,12,],[0,-1,-3,]),'NAMESPACE':([2,8,],[5,-2,]),'IDENTIFICADOR':([3,5,11,23,],[6,7,13,24,]),'SEMICOLON':([6,34,],[8,35,]),'LBRACE':([7,13,25,],[9,14,26,]),'CLASS':([9,],[11,]),'RBRACE':([10,15,17,27,29,35,],[12,17,-4,29,-5,-6,]),'STATIC':([14,],[16,]),'VOID':([16,],[18,]),'MAIN':([18,],[19,]),'LPAREN':([19,31,],[20,32,]),'STRING':([20,],[21,]),'LBRACKET':([21,],[22,]),'RBRACKET':([22,],[23,]),'RPAREN':([24,33,],[25,34,]),'CONSOLE':([26,],[28,]),'DOT':([28,],[30,]),'WRITELINE':([30,],[31,]),'CADENA':([32,],[33,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'using_decl':([0,],[2,]),'namespace_decl':([2,],[4,]),'class_decl':([9,],[10,]),'method_decl':([14,],[15,]),'statement':([26,],[27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> using_decl namespace_decl','programa',2,'p_programa','app.py',76),
  ('using_decl -> USING IDENTIFICADOR SEMICOLON','using_decl',3,'p_using_decl','app.py',81),
  ('namespace_decl -> NAMESPACE IDENTIFICADOR LBRACE class_decl RBRACE','namespace_decl',5,'p_namespace_decl','app.py',84),
  ('class_decl -> CLASS IDENTIFICADOR LBRACE method_decl RBRACE','class_decl',5,'p_class_decl','app.py',87),
  ('method_decl -> STATIC VOID MAIN LPAREN STRING LBRACKET RBRACKET IDENTIFICADOR RPAREN LBRACE statement RBRACE','method_decl',12,'p_method_decl','app.py',90),
  ('statement -> CONSOLE DOT WRITELINE LPAREN CADENA RPAREN SEMICOLON','statement',7,'p_statement','app.py',93),
]
